{
 "title": "Fremont",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Fatal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RedFishEvents_received{Severity=\"Fatal\"}[$__range])) by (Severity))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RedFishEvents_received{Severity=\"Critical\"}[$__range])) by (Severity))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Informational",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(RedFishEvents_received{Severity=\"Informational\"}[$__range])) by (Severity))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(sum by(Severity) (increase(RedFishEvents_received[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}